#!/bin/sh
cat <<'EOF' >main.c
#include <stdio.h>

void	ft_rev_int_tab(int *tab, int size);

void	ft_print_array_ptr(int *arr, int size)
{
	int	i;

	i = 0;
	while (i <= size - 1)
	{
		printf("arr[%d]: %d | ", i, arr[i]);
		++i;
	}
	printf("\n");
}

int	main(void)
{
	int	table[10];

	table[0] = 10;
	table[1] = 20;
	table[2] = 30;
	table[3] = 40;
	table[4] = 50;
	table[5] = 60;
	table[6] = 70;
	table[7] = 80;
	table[8] = 90;
	table[9] = 100;

	ft_print_array_ptr(table, 10);
	ft_rev_int_tab(table, 10);
	ft_print_array_ptr(table, 10);
}
EOF
