#!/bin/sh
cat <<'EOF' >main.c
#include <stdio.h>

void	ft_swap(int *a, int *b);

int	main(void)
{
	int a = 111222;
	int b = 333444;
	int *alpha;
	int *beta;

	alpha=&a;
	beta=&b;
	printf("alpha: %d | beta: %d\n", *alpha, *beta);
	ft_swap(alpha, beta);
	printf("alpha: %d | beta: %d\n", *alpha, *beta);
}
EOF
