#!/bin/sh
cat <<'EOF' >main.c
#include <stdio.h>

void	ft_ultimate_div_mod(int *a, int *b);

int	main(void)
{
	int a = 500;
	int b = 15;
	int *alpha;
	int *beta;

	alpha=&a;
	beta=&b;
	printf("alpha: %d | beta: %d\n", *alpha, *beta);
	ft_ultimate_div_mod(alpha, beta);
	printf("alpha: %d | beta: %d\n", *alpha, *beta);
}
EOF
