#!/bin/sh
if [ $1 == "ex00" ] ; then
	ft_strcpy
fi
if [ $1 == "ex01" ] ; then
	ft_strncpy
fi
if [ $1 == "ex02" ] ; then
	ft_
fi
if [ $1 == "ex03" ] ; then
	ft_
fi
if [ $1 == "ex04" ] ; then
	ft_
fi
if [ $1 == "ex05" ] ; then
	ft_
fi
if [ $1 == "ex06" ] ; then
	ft_
fi
if [ $1 == "ex07" ] ; then
	ft_
fi
if [ $1 == "ex08" ] ; then
	ft_
fi
