#!/bin/sh
find . -type f -name "_ft_*" -exec rm {} \; 2>/dev/null
find . -type d -name "obj" -exec rm -rf {} \; 2>/dev/null
find . -type f -name "main.c" -exec rm {} \; 2>/dev/null
find . -type f -name "1" -exec rm {} \; 2>/dev/null
echo "Cleaned ${PWD##*/}"