#!/bin/sh
cat <<'EOF' >main.c
#include <stdio.h>

char	*ft_strncpy(char *dest, char *src, unsigned int n);

int	main(void)
{
	char init[]="aaaaa";
	char blah[]="bbbbb";
	printf("init: %s | blah: %s\n", init, blah);
	ft_strncpy(init, blah, 3);
	printf("init: %s | blah: %s\n", init, blah);
}
EOF
