#!/bin/sh
if [ $1 == "ex00" ] ; then
	ft_ft
fi
if [ $1 == "ex01" ] ; then
	ft_ultimate_ft
fi
if [ $1 == "ex02" ] ; then
	ft_swap
fi
if [ $1 == "ex03" ] ; then
	ft_print_numbers
fi
if [ $1 == "ex04" ] ; then
	ft_is_negative
fi
if [ $1 == "ex05" ] ; then
	ft_print_comb
fi
if [ $1 == "ex06" ] ; then
	ft_print_comb2
fi
if [ $1 == "ex07" ] ; then
	ft_putnbr
fi
if [ $1 == "ex08" ] ; then
	ft_print_combn
fi
