#!/bin/sh
find . -type f -name "_ft_*" -print -exec rm {} \; 2>/dev/null
find . -type d -name "obj" -print -exec rm -rf {} \; 2>/dev/null
find . -type f -name "main.c" -print -exec rm {} \; 2>/dev/null
find . -type f -name "1" -print -exec rm {} \; 2>/dev/null