#!/bin/sh
cat <<'EOF' >main.c
#include <stdio.h>

char	*ft_strcpy(char *dest, char *src);

int	main(void)
{
	char init[]="aa";
	char blah[]="dddddddddd";
	printf("init: %s | blah: %s\n", init, blah);
	ft_strcpy(init, blah);
	printf("init: %s | blah: %s\n", init, blah);
}
EOF
