#!/bin/sh
cat <<'EOF' >main.c
#include <unistd.h>

void	ft_swap(int *a, int *b);

void	ft_putchar(char c)
{
	write(1, &c, 1);
}

void	ft_putnbr(int n)
{
	unsigned int	nbr;

	if (n < 0)
	{
		ft_putchar('-');
		nbr = n * -1;
	}
	else
		nbr = n;
	if (nbr >= 10)
		ft_putnbr(nbr / 10);
	ft_putchar(nbr % 10 + 48);
}

int	main(void)
{
	int a;
	int b;
	int *alpha;
	int *beta;

	a=20;
	b=42;
	alpha=&a;
	beta=&b;
	ft_putnbr(*alpha);
	ft_putchar('\n');
	ft_putnbr(*beta);
	ft_putchar('\n');
	ft_swap(alpha, beta);
	ft_putnbr(*alpha);
	ft_putchar('\n');
	ft_putnbr(*beta);
	ft_putchar('\n');
}
EOF
