#!/bin/sh
if [ $1 == "ex00" ] ; then
	~/.shiva/templates/ft_ft
fi
if [ $1 == "ex01" ] ; then
	~/.shiva/templates/ft_ultimate_ft
fi
if [ $1 == "ex02" ] ; then
	~/.shiva/templates/ft_swap
fi
if [ $1 == "ex03" ] ; then
	~/.shiva/templates/ft_div_mod
fi
if [ $1 == "ex04" ] ; then
	~/.shiva/templates/ft_ultimate_div_mod
fi
if [ $1 == "ex05" ] ; then
	~/.shiva/templates/ft_putstr
fi
if [ $1 == "ex06" ] ; then
	~/.shiva/templates/ft_strlen
fi
if [ $1 == "ex07" ] ; then
	~/.shiva/templates/ft_rev_int_table
fi
if [ $1 == "ex08" ] ; then
	~/.shiva/templates/ft_sort_int_table
fi
